config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show]
  resource  :session, only: [:new, :create, :destroy]
  resources :bands, only: [:index, :new, :create, :destroy, :show, :update, :edit] do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :destroy, :show, :update, :edit] do
    resources :tracks, only: [:new]
  end
  resources :tracks, only: [:create, :destroy, :show, :update, :edit]

end

app/models/album.rb
class Album < ActiveRecord::Base
  validates :album_name, :band_id, presence: true

  belongs_to(
    :band,
    class_name: "Band",
    foreign_key: :band_id,
    primary_key: :id
  )

  has_many(
    :tracks,
    class_name: "Track",
    foreign_key: :album_id,
    primary_key: :id
  )

end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true

  belongs_to(
    :owner,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )

  has_many(
    :albums,
    class_name: "Album",
    foreign_key: :band_id,
    primary_key: :id
  )


end

app/models/track.rb
class Track < ActiveRecord::Base

  belongs_to(
    :album,
    class_name: "Album",
    foreign_key: :album_id,
    primary_key: :id
  )
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :password_digest, :session_token, presence: true
  validates :email, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}
  attr_reader :password

  after_initialize :ensure_session_token

  has_many(
    :bands,
    class_name: "Band",
    foreign_key: :user_id,
    primary_key: :id
  )



  def self.generate_session_token
     SecureRandom::urlsafe_base64
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user
    user.is_password?(password) ? user : nil
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
    self.save
  end

  def is_password?(password)
    bc_password = BCrypt::Password.new(self.password_digest)
    bc_password.is_password?(password)
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def create
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def logged_in?
    return true if current_user
    false
  end

  def log_in(user)
    session[:session_token] = user.session_token
  end

  def log_out
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
  end

  def create
  end

  def show
    @band = Band.find(params[:id])
    @albums = @band.albums
  end

  def update
  end

  def destroy
  end

  def edit
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(user_params[:email], user_params[:password])
    if user
      log_in(user)
      flash[:message] = "Welcom back"
      redirect_to user_url(user)
    else
      flash.now[:errors] = ["Invalid credentials"]
      render :new
    end
  end

  def destroy
    log_out
    flash.now[:message] = "Ciao!"
    redirect_to new_session_url
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :session_token)
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    #create new user
    user = User.new(email: user_params[:email], password: user_params[:password])
    if user.save
      log_in(user)
      redirect_to user_url(user) # will render show!!!
    else
      flash.now[:errors] = user.errors.full_messages #an array
      render :new
    end
  end

  def show
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bands/_form_band.html.erb
<form action="<% action %>" method="post">
<!-- a list of albums -->
<!-- some links that allow you to updat/create etc -->
  <!-- print out the name of current scope (band, album...) -->
  <h1><%= band.name %></h1>

  <!-- list albums -->
  <% unless band.albums.empty? %>
  <label for="albums">Albums</label>
    <ul>
      <% band.albums.each do |album| %>
        <li><%= link_to album.album_name, album_url %></li>
      <% end %>
    </ul>
  <% end %>




  <!-- edit stuffs -->
  <label for="links">Links</label>
  <ul>
    <li><%= link_to "New Track", tracks_url, method: :post%></li>
    <li><%= link_to "Edit Album", edit_album_url, method: :get%></li>
    <li><%= link_to "Delete Album", album_url, method: :delete%></li>
    <li><%= link_to "All Bands", bands_url, method: :get %></li>
  </ul>

</form>

app/views/bands/index.html.erb
<h1>Welcome <%= current_user.email %> </h1>
<% unless Band.all.empty? %>
<ul>
  <% Band.all.each do |band| %>
  <li><%= link_to band.name, band_url(band)%></li>
  <% end %>
</ul>
<% end %>
<%= button_to "Log out", new_session_url, method: :get %>

app/views/bands/show.html.erb
<!-- <h1><%= @band.name %></h1>

<ul>
  <% @albums.each do |album| %>
      <li><%= album.album_name %></li>
  <% end %>
</ul> -->
<%= render "shared/form_band", band: @band, action: band_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Music</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/session/login.html.erb
<h1>Sign In!!</h1>
<%= render "shared/form" %>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <ul>
      <% flash[:errors].each do |error| %>
      <li><%= error %></li>
      <% end %>
  </ul>
<% end %>

app/views/shared/_form.html.erb
<form action="<%=action%>", method="<%=method%>">
  <%= render "shared/errors" %>
  <label for="user_email">Email</label>
  <input type=text name="user[email]" id="user_email">

  <label for="user_password">Password</label>
  <input type=text name="user[password]" id ="user_password">

  <input type="submit">
</form>

app/views/users/new.html.erb
<h1>Sign up Now! for 100+ free musics</h1>
<!-- <img src="assets/music1.jpg" alt="music" style="width:300px;height:200px;"> -->
<%= render "shared/form", action: users_url, method: "post"%>
<%= link_to "Sign in", new_session_url, method: :get %>

app/views/users/show.html.erb
<h1>Welcome ! <%= current_user.email %></h1>

<%= link_to "Go to all bands", bands_url, method: :get %>
<%= button_to "Log out", session_url, method: :delete %>